### PR TITLE
Added fifth ar marker

### PR DESCRIPTION
**Pull request by lianilychee**
Added fifth ar marker to eliminate dead zone.
Make sure to `git pull upstream master` in `ar_tools`, which is located in `catkin_ws/src`.
Connect to a single bot using the usual routine (`python scripts/multi_connect.py`, set thresholds with `rqt_gui`).
Open `rviz` and add the topics `STAR_pose` and `STAR_pose_continuous`, setting the arrows to different colors.  Make sure the frame is set to `STAR`.
Drive the robot around the arena with teleop.  Observe that there are no discrepancies with the `STAR_pose` and `STAR_pose_continuous` arrows.

### CODE REVIEW

**Comment by jacobkingery** [comment]
Please submit a pull request to merge into the `dev` branch rather than `master`

**Comment by jacobkingery** [comment]
Also, please do not commit temporary backup files (those ending with ~).

**Comment by jacobkingery** [comment]
I'm a bit confused about the name change from `4x4` to `5x5`.  The numbers refer to the dimensions of the markers (4 by 4 blocks), not to the number of markers being used.  Is there a reason for creating a new file instead of just editing the old `object_4x4` in `ar_pose`?

**Comment by lianilychee** [comment]
I MESSED UP I'M SORRY

**Pull request closed without merging**
